[project]
name = "flask_app"
version = "0.1.0"
description = "understand package pattern"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"