"""empty message

Revision ID: 995a7656e229
Revises: 
Create Date: 2025-04-27 11:54:16.251084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995a7656e229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('Job', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
